spring:
  profiles:
    active:       #加载运行环境
  thymeleaf:      #配置thymeleaf模板
    cache: false  # 开发时关闭缓存,不然没法看到实时页面
  datasource:     #数据源配置
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/dongdong
    driver-class-name: com.mysql.jdbc.Driver #将spring boot默认的连接池改成德鲁伊的连接池
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: [stat,wall,log4j]      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  config-location: classpath:sqlMapConfig.xml
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.dk.pojo

logging:
  level:
    com:
      dk: debug
  file:
    path: D:/logs/springboot.log

